# Generated by scripts/generate-homebrew-formula.mjs in yusufaf/sfn-diagram.
# Do not edit by hand; the release workflow overwrites this file on every release.
class SfnDiagram < Formula
  desc "Generate SVG, Mermaid, and HTML diagrams from AWS Step Functions definitions"
  homepage "https://sfn.yusufaf.dev"
  version "1.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.8.0/sfn-diagram-darwin-arm64"
      sha256 "758e2d41247c24cd04c05c9c94528e10690e6e11af9e475c1947d2789d00e96a"
    end
    on_intel do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.8.0/sfn-diagram-darwin-x64"
      sha256 "25490bc4f52314d8b3b94e72c0446be33abd1235b48ec4f7db90613666222f95"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.8.0/sfn-diagram-linux-arm64"
      sha256 "ccb376509a79bedf922b06f8f69b8306d25d44121332b01ffadfc1e1ec13556c"
    end
    on_intel do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.8.0/sfn-diagram-linux-x64"
      sha256 "7287572c3c2837ceebf527af816caed02e44be39daff1723bd6d8c4a23435202"
    end
  end

  def install
    bin.install Dir["sfn-diagram-*"].first => "sfn-diagram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sfn-diagram --version")
    (testpath/"simple.asl.json").write <<~EOS
      {"StartAt":"Hello","States":{"Hello":{"Type":"Pass","End":true}}}
    EOS
    assert_match "<svg", shell_output("#{bin}/sfn-diagram #{testpath}/simple.asl.json --format svg")
  end
end
