# Generated by scripts/generate-homebrew-formula.mjs in yusufaf/sfn-diagram.
# Do not edit by hand; the release workflow overwrites this file on every release.
class SfnDiagram < Formula
  desc "Generate SVG, Mermaid, and HTML diagrams from AWS Step Functions definitions"
  homepage "https://sfn.yusufaf.dev"
  version "1.6.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.0/sfn-diagram-darwin-arm64"
      sha256 "2b16cc2076a290ca3047a218a1a5cd4dca2b29cee14faa6cd29b15d1b44121ac"
    end
    on_intel do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.0/sfn-diagram-darwin-x64"
      sha256 "bdab13c9b5954eda5954854c8b90cff0e993305a18979670f376e9f202317e07"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.0/sfn-diagram-linux-arm64"
      sha256 "e7b7174b99c878f493d98f68fc71a7906b74e96f1b8e2cbebc659effb0b2a21b"
    end
    on_intel do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.0/sfn-diagram-linux-x64"
      sha256 "ee1a60f0839e15bc9c155cee421ac58ee42b536196a0d41b758b98c5803ce0d3"
    end
  end

  def install
    bin.install Dir["sfn-diagram-*"].first => "sfn-diagram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sfn-diagram --version")
    (testpath/"simple.asl.json").write <<~EOS
      {"StartAt":"Hello","States":{"Hello":{"Type":"Pass","End":true}}}
    EOS
    assert_match "<svg", shell_output("#{bin}/sfn-diagram #{testpath}/simple.asl.json --format svg")
  end
end
