# Generated by scripts/generate-homebrew-formula.mjs in yusufaf/sfn-diagram.
# Do not edit by hand; the release workflow overwrites this file on every release.
class SfnDiagram < Formula
  desc "Generate SVG, Mermaid, and HTML diagrams from AWS Step Functions definitions"
  homepage "https://sfn.yusufaf.dev"
  version "1.6.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.1/sfn-diagram-darwin-arm64"
      sha256 "16e925c5a9616238be8c66adac3b4f4c4b54f2e283058cddaaf5b76a335dc7c1"
    end
    on_intel do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.1/sfn-diagram-darwin-x64"
      sha256 "5f47eb50889cf247e50aa0e40992cddb7a7a7138735807d60ec413cc39e62d20"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.1/sfn-diagram-linux-arm64"
      sha256 "72fc095160ac6f1ef40c3cdde52f35cd82b0c5f60f4ca08cc52167f9cb7964e8"
    end
    on_intel do
      url "https://github.com/yusufaf/sfn-diagram/releases/download/sfn-diagram-v1.6.1/sfn-diagram-linux-x64"
      sha256 "6353782d448ef94a8e115b09e72fcae292082860e6f79b4761b36cd340afd71f"
    end
  end

  def install
    bin.install Dir["sfn-diagram-*"].first => "sfn-diagram"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sfn-diagram --version")
    (testpath/"simple.asl.json").write <<~EOS
      {"StartAt":"Hello","States":{"Hello":{"Type":"Pass","End":true}}}
    EOS
    assert_match "<svg", shell_output("#{bin}/sfn-diagram #{testpath}/simple.asl.json --format svg")
  end
end
